# SPDX-FileCopyrightText: 2021 Free Software Foundation Europe <https://fsfe.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

FROM python:3.8-slim

MAINTAINER Free Software Foundation Europe <system-hackers@lists.fsfe.org>

RUN pip3 install --no-cache-dir pipenv
